---
- name: Item 6.3 - Instalar Apache en puerto 9999
  hosts: local
  become: yes
  tasks:
    - name: Instalar Apache (apache2)
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Configurar Apache para escuchar en el puerto 9999
      copy:
        content: "Listen 9999\n"
        dest: /etc/apache2/ports.conf

    - name: Cambiar el VirtualHost por defecto al puerto 9999
      replace:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: '<VirtualHost \*:80>'
        replace: '<VirtualHost *:9999>'

    - name: Reiniciar Apache
      service:
        name: apache2
        state: restarted
